### ISSUE TITLE
Fix CallbackQuery behaviour

### ISSUE THREAD

**Issue by voed** [AleXr64/Telegram-bot-framework#120]
CallbackQuery не содержит поле Chat, вместо него есть ChatInstance с айдишником чата.

**Comment by CrazyHackGUT** [comment]
`ChatInstance` не айдишник чата, но его можно выцепить из `Message`. Из флудилки запротоколирую.

**Comment by voed** [comment]
Fixed by https://github.com/AleXr64/Telegram-bot-framework/commit/4c3d595f638df1e6b095776461213db6bb513b78
