### ISSUE TITLE
Добавить новые типы апдейтов MyChatMember и ChatMember

### ISSUE THREAD

**Issue by voed** [AleXr64/Telegram-bot-framework#57]
```        //
        // Summary:
        //     The Telegram.Bot.Types.Update contains an Telegram.Bot.Types.Enums.UpdateType.MyChatMember
        MyChatMember = 12,
        //
        // Summary:
        //     The Telegram.Bot.Types.Update contains an Telegram.Bot.Types.Enums.UpdateType.ChatMember
        ChatMember = 13
```

**Comment by azhe403** [comment]
How to use thats?
Break point at line 20 is never fired.

![gambar](https://user-images.githubusercontent.com/17938038/132100739-ed20a01a-5c49-4ca1-b659-523feaace852.png)

**Comment by voed** [comment]
From Telegram API reference:
![image](https://user-images.githubusercontent.com/10352360/132108270-95665c9b-1af7-413d-bc5e-36478256ff25.png)
I will try to test it later
