### ISSUE TITLE
Command without /

### ISSUE THREAD

**Issue by azhe403** [AleXr64/Telegram-bot-framework#68]
How to call command with and without "/" like "/ping" and "ping"

```
        Command("ping", CommandParseMode.Both)]
        public async Task Ping()
        {
            var send = await Bot.SendTextMessageAsync(Chat, "Pong!");

            await Task.Delay(2000);

            await Bot.EditMessageTextAsync(Chat, send.MessageId, "Hehey");
        }
```

**Comment by AleXr64** [comment]
In stable version (0.3.x) you can use ```TextMessage``` attribute for handle keywords

**Comment by voed** [comment]
For 0.3:
```cs
        [TextMessage("ping", CommandParseMode.Both)]
        public async Task Ping()
         . . .
```

And if you are using 0.5.x pre-release version:
```cs
        //Answer on message with "ban" text
        [Message("ban")]
        public async Task Ban() => await Bot.SendTextMessageAsync(Chat, "I will ban you right now! Just kidding");

        //Answer on message that satisfy provided regex expression
        [Message("^.*?(?i)python$", regex: true)]
        public async Task Task() => await Bot.SendTextMessageAsync(Chat, "I hate snakes");
```

**Comment by azhe403** [comment]
> 
> 
> For 0.3:
> 
> ```cs
>         [TextMessage("ping", CommandParseMode.Both)]
>         public async Task Ping()
>          . . .
> ```
> 
> And if you are using 0.5.x pre-release version:
> 
> ```cs
>         //Answer on message with "ban" text
>         [Message("ban")]
>         public async Task Ban() => await Bot.SendTextMessageAsync(Chat, "I will ban you right now! Just kidding");
> 
>         //Answer on message that satisfy provided regex expression
>         [Message("^.*?(?i)python$", regex: true)]
>         public async Task Task() => await Bot.SendTextMessageAsync(Chat, "I hate snakes");
> ```

I has update lib to 0.5.16-xxx and have regex pattern like this for handle both "ping" and "/ping".

![image](https://user-images.githubusercontent.com/17938038/128963192-fab24ae7-b973-435b-aedc-d35b78e3bdfe.png)

When applying to atribute seem not working because no response `ping`

![image](https://user-images.githubusercontent.com/17938038/128962928-8c228290-9df1-4bb4-bcb2-48652ce95df6.png)

can you help me?

**Comment by voed** [comment]
Um, i guess you cannot use inline options like this in dotnet.
Your regular expression should be like this:
```cs
        [Message("/?(?i)ping", regex: true)]
        public async Task Ping()
        {
            await Bot.SendTextMessageAsync(Chat, "Pong");
        }
```
Use dotnet regex validator instead of JS (for example http://regexstorm.net/tester or regex101 with java/golang mode).
We will add possibility to use RegexOptions in future.
