### ISSUE TITLE
Create own EventHandler

### ISSUE THREAD

**Issue by azhe403** [AleXr64/Telegram-bot-framework#70]
If we need more property instead of default on `BotEventHandler`, look good if we can create our own EventHandler.

![image](https://user-images.githubusercontent.com/17938038/129176606-5582b5ca-1d0d-4f0c-8554-e7519c6f605d.png)

I'm try to create own EventHandler, but there cant be abstracted

![image](https://user-images.githubusercontent.com/17938038/129177418-d7e96149-75b0-4a0a-a2a7-a313ebe0189b.png)

One or more of object seem need to be instantiated.

![image](https://user-images.githubusercontent.com/17938038/129177062-f8ea45ac-55f4-4737-b882-1642d55021b0.png)
![image](https://user-images.githubusercontent.com/17938038/129177582-0db12473-a00c-46eb-8316-d161de6437c0.png)

Any simple way to create own Handler?
Sory bad my English

**Comment by AleXr64** [comment]
What is the reason for creating own handler? Why not inheritance?

**Comment by voed** [comment]
Its not necessary to implement your own handler in this case. You can use `RawUpdate` to access update data.
```cs
public async Task Ping()
{
    var time = RawUpdate.Message.Date.GetDelay()
}
```

**Comment by azhe403** [comment]
> 
> 
> Its not necessary to implement your own handler in this case. You can use `RawUpdate` to access update data.
> 
> ```cs
> public async Task Ping()
> {
>     var time = RawUpdate.Message.Date.GetDelay()
> }
> ```

like that's, but i need every class have property `time` like an inherited class.

**Comment by AleXr64** [comment]
> like that's, but i need every class have property `time` like an inherited class.

Just use ```RawUpdate``` instead of ```_params.Update``` here and not override ```_params``` and internal method
![изображение](https://user-images.githubusercontent.com/26191634/129183158-d2ad6771-8c50-435d-947a-212516b83af5.png)

**Comment by azhe403** [comment]
> 
> 
> > like that's, but i need every class have property `time` like an inherited class.
> 
> Just use `RawUpdate` instead of `_params.Update` here and not override `_params` and internal method
> ![изображение](https://user-images.githubusercontent.com/26191634/129183158-d2ad6771-8c50-435d-947a-212516b83af5.png)

Ah, I see. Sorry my misunderstand.
Little forgot about an inheritance.

Thanks for this great lib!
I'll close this issue :)
